### ISSUE TITLE
Plugin is not functional.

### ISSUE THREAD

**Issue by RealTriassic** [OskarsMC-Plugins/broadcast#1]

**Comment by RealTriassic** [comment]
Oops sorry, here's the error.

[23:48:58 INFO]: Exception occurred while running command for Triassic
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to invoke command broadcast text test for [connected player] Triassic (/SNIPSNIP:52237)
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1766) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.RuntimeException: Unable to invoke command broadcast text test for [connected player] Triassic (/SNIPSNIP:52237)
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately(VelocityCommandManager.java:184) ~[server.jar:1.1.8]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:209) ~[server.jar:1.1.8]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
        ... 3 more
Caused by: java.lang.IllegalArgumentException: No such argument 'context' exists on this command
        at com.mojang.brigadier.context.CommandContext.getArgument(CommandContext.java:101) ~[server.jar:1.1.8]
        at com.oskarsmc.broadcast.command.BroadcastBrigadier.lambda$new$1(BroadcastBrigadier.java:45) ~[?:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[server.jar:1.1.8]
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately(VelocityCommandManager.java:171) ~[server.jar:1.1.8]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:209) ~[server.jar:1.1.8]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
        ... 3 more

**Comment by RealTriassic** [comment]
I got this when i ran /broadcast text test

**Comment by OskarZyg** [comment]
I know that there’s a lot wrong with this plugin right now, I’ll rewrite it and fix.

**Comment by OskarZyg** [comment]
Could you test out [this build](https://github.com/OskarsMC-Plugins/broadcast/actions/runs/962194764) for me?

**Comment by OskarZyg** [comment]
Feel free to create a new issue if there are more issues, ill go on to release this.

**Comment by ggtylerr** [comment]
Hi there, I'm not sure if this is the same issue the person above was facing, but when trying this on my own proxy, I couldn't run broadcast at all. Running it in console gave an incorrect argument error. I'm guessing this isn't supposed to be for 3.0.0.

Here's the error (yes, this is all it logged):
```
23.07 03:59:10 [Server] INFO Incorrect argument for command at position 10: broadcast <--[HERE]
23.07 03:59:10 [PebbleHost] ggtylerr_contact@protonmail.com ran command: broadcast test
```

**Comment by OskarZyg** [comment]
Firstly, you appear to be running that command on a spigot server the logging and the error is different than a usual velocity enviroment), this plugin works perfectly fine in velocity 3.0.0
```text
>....[10:50:58 INFO]: /velocity <version|plugins|reload|dump>
>....[10:51:08 INFO]: Velocity 3.0.0
[10:51:08 INFO]: Copyright 2018-2021 Velocity Contributors. Velocity is licensed under the terms of the GNU General Public License v3.
[10:51:08 INFO]: velocitypowered.com - GitHub
>....[10:51:16 INFO]: Plugins: {0}broadcast, luckperms, message, quantum-motd, send, spark, tcpshield, twitch
>....[10:51:26 INFO]: Invalid Command Syntax. Correct command syntax is: broadcast minimessage|raw|text
```

**Comment by ggtylerr** [comment]
Nope, on a Velocity server. Pebblehost just likes to force its looks on console.

```
23.07 06:22:30 [Server] INFO Velocity 3.0.0
23.07 06:22:30 [Server] INFO Copyright 2018-2021 Velocity Contributors. Velocity is licensed under the terms of the GNU General Public License v3.
23.07 06:22:30 [Server] INFO velocitypowered.com - GitHub
23.07 06:22:30 [PebbleHost] ggtylerr_contact@protonmail.com ran command: velocity version
23.07 06:22:38 [PebbleHost] ggtylerr_contact@protonmail.com ran command: broadcast test
23.07 06:22:38 [Server] INFO Incorrect argument for command at position 10: broadcast <--[HERE]
```

**Comment by OskarZyg** [comment]
What version of the plugin are you running?

**Comment by ggtylerr** [comment]
[This one](https://github.com/OskarsMC-Plugins/broadcast/releases/tag/1.0.0)

**Comment by OskarZyg** [comment]
What arguments are you using with broadcast?

**Comment by OskarZyg** [comment]
You aren't using the correct arguments, take a look at https://github.com/OskarsMC-Plugins/broadcast/blob/main/README.md

**Comment by OskarZyg** [comment]
eg: `/broadcast text test`

**Comment by ggtylerr** [comment]
...Why doesn't it default to text?

Edit: Also, how do I get ampersands to work?

**Comment by OskarZyg** [comment]
I'll add the default to text soon, ampersands are very old and have been deprecated by Mojang since 2012-2013, as such I will not be supporting them.
